# Generated by Django 3.1 on 2021-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('gallery', 'GALLERY'), ('carousel', 'CAROUSEL')], default='gallery', max_length=64),
        ),
    ]
