# Generated by Django 3.1 on 2021-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210802_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_times',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
