# Generated by Django 3.1 on 2021-08-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210802_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='opening_times',
            new_name='opening_times_en',
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_times_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_times_tk',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_times_uz',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
