# Generated by Django 3.1 on 2021-08-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210802_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
