# Generated by Django 3.1 on 2021-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210802_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
