# Generated by Django 3.1 on 2021-08-03 18:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('responsibility_uz', models.CharField(blank=True, max_length=64, null=True)),
                ('responsibility_en', models.CharField(blank=True, max_length=64, null=True)),
                ('responsibility_ru', models.CharField(blank=True, max_length=64, null=True)),
                ('responsibility_tk', models.CharField(blank=True, max_length=64, null=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_tk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=64, null=True)),
                ('twitter', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
